
import { ARM7CPU } from '../cpu';
import * as arm from './arm/arm';
export type opHandler = (cpu: ARM7CPU) => void;

export const armOpTable:  StaticArray<StaticArray<opHandler | null>> = [




/** 0x0 **/[ arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.MUL, arm.AND, arm.STRH, arm.AND, null, arm.AND, null],
/** 0x1 **/[ arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.MUL, arm.AND, arm.LDRH, arm.AND, arm.LDRSB, arm.AND, arm.LDRSH],
/** 0x2 **/[ arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.MLA, arm.EOR, arm.STRH, arm.EOR, null, arm.EOR, null],
/** 0x3 **/[ arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.MLA, arm.EOR, arm.LDRH, arm.EOR, arm.LDRSB, arm.EOR, arm.LDRSH],
/** 0x4 **/[ arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, null, arm.SUB, arm.STRH, arm.SUB, null, arm.SUB, null],
/** 0x5 **/[ arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, null, arm.SUB, arm.LDRH, arm.SUB, arm.LDRSB, arm.SUB, arm.LDRSH],
/** 0x6 **/[ arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, null, arm.RSB, arm.STRH, arm.RSB, null, arm.RSB, null],
/** 0x7 **/[ arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, null, arm.RSB, arm.LDRH, arm.RSB, arm.LDRSB, arm.RSB, arm.LDRSH],
/** 0x8 **/[ arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.UMULL, arm.ADD, arm.STRH, arm.ADD, null, arm.ADD, null],
/** 0x9 **/[ arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.UMULL, arm.ADD, arm.LDRH, arm.ADD, arm.LDRSB, arm.ADD, arm.LDRSH],
/** 0xa **/[ arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.UMLAL, arm.ADDC, arm.STRH, arm.ADDC, null, arm.ADDC, null],
/** 0xb **/[ arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.UMLAL, arm.ADDC, arm.LDRH, arm.ADDC, arm.LDRSB, arm.ADDC, arm.LDRSH],
/** 0xc **/[ arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SMLUL, arm.SBC, arm.STRH, arm.SBC, null, arm.SBC, null],
/** 0xd **/[ arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SMLUL, arm.SBC, arm.LDRH, arm.SBC, arm.LDRSB, arm.SBC, arm.LDRSH],
/** 0xe **/[ arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.SMLAL, arm.RSC, arm.STRH, arm.RSC, null, arm.RSC, null],
/** 0xf **/[ arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.SMLAL, arm.RSC, arm.LDRH, arm.RSC, arm.LDRSB, arm.RSC, arm.LDRSH],
/** 0x10 **/[arm.MRS, null,null, null,null, null,null, null,null, arm.SWP,null, arm.STRH,null, null,null, null],
/** 0x11 **/[ arm.TST, arm.TST, arm.TST, arm.TST, arm.TST, arm.TST, arm.TST, arm.TST, arm.TST, null, arm.TST, arm.LDRH, arm.TST, arm.LDRSB, arm.TST, arm.LDRSH],
/** 0x12 **/[arm.MSR, null,null, null,null, null,null, null,null, null,null, arm.STRH,null, null,null, null],
/** 0x13 **/[ arm.TEQ, arm.TEQ, arm.TEQ, arm.TEQ, arm.TEQ, arm.TEQ, arm.TEQ, arm.TEQ, arm.TEQ, null, arm.TEQ, arm.LDRH, arm.TEQ, arm.LDRSB, arm.TEQ, arm.LDRSH],
/** 0x14 **/[arm.MRS, null,null, null,null, null,null, null,null, arm.SWPB,null, arm.STRH,null, null,null, null],
/** 0x15 **/[ arm.CMP, arm.CMP, arm.CMP, arm.CMP, arm.CMP, arm.CMP, arm.CMP, arm.CMP, arm.CMP, null, arm.CMP, arm.LDRH, arm.CMP, arm.LDRSB, arm.CMP, arm.LDRSH],
/** 0x16 **/[arm.MSR, null,null, null,null, null,null, null,null, null,null, arm.STRH,null, null,null, null],
/** 0x17 **/[ arm.CMN, arm.CMN, arm.CMN, arm.CMN, arm.CMN, arm.CMN, arm.CMN, arm.CMN, arm.CMN, null, arm.CMN, arm.LDRH, arm.CMN, arm.LDRSB, arm.CMN, arm.LDRSH],
/** 0x18 **/[ arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, null, arm.ORR, arm.STRH, arm.ORR, null, arm.ORR, null],
/** 0x19 **/[ arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, null, arm.ORR, arm.LDRH, arm.ORR, arm.LDRSB, arm.ORR, arm.LDRSH],
/** 0x1a **/[ arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, null, arm.MOV, arm.STRH, arm.MOV, null, arm.MOV, null],
/** 0x1b **/[ arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, null, arm.MOV, arm.LDRH, arm.MOV, arm.LDRSB, arm.MOV, arm.LDRSH],
/** 0x1c **/[ arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, null, arm.BIC, arm.STRH, arm.BIC, null, arm.BIC, null],
/** 0x1d **/[ arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, null, arm.BIC, arm.LDRH, arm.BIC, arm.LDRSB, arm.BIC, arm.LDRSH],
/** 0x1e **/[ arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, null, arm.MVN, arm.STRH, arm.MVN, null, arm.MVN, null],
/** 0x1f **/[ arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, null, arm.MVN, arm.LDRH, arm.MVN, arm.LDRSB, arm.MVN, arm.LDRSH],
/** 0x20 **/[ arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND],
/** 0x21 **/[ arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND, arm.AND],
/** 0x22 **/[ arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR],
/** 0x23 **/[ arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR, arm.EOR],
/** 0x24 **/[ arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB],
/** 0x25 **/[ arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB, arm.SUB],
/** 0x26 **/[ arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB],
/** 0x27 **/[ arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB, arm.RSB],
/** 0x28 **/[ arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD],
/** 0x29 **/[ arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD, arm.ADD],
/** 0x2a **/[ arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC],
/** 0x2b **/[ arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC, arm.ADDC],
/** 0x2c **/[ arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC],
/** 0x2d **/[ arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC, arm.SBC],
/** 0x2e **/[ arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC],
/** 0x2f **/[ arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC, arm.RSC],
/** 0x30 **/[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
/** 0x31 **/[ arm.TST, arm.TST, arm.TST, arm.TST, arm.TST, arm.TST, arm.TST, arm.TST, arm.TST, arm.TST, arm.TST, arm.TST, arm.TST, arm.TST, arm.TST, arm.TST],
/** 0x32 **/[arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR],
/** 0x33 **/[ arm.TEQ, arm.TEQ, arm.TEQ, arm.TEQ, arm.TEQ, arm.TEQ, arm.TEQ, arm.TEQ, arm.TEQ, arm.TEQ, arm.TEQ, arm.TEQ, arm.TEQ, arm.TEQ, arm.TEQ, arm.TEQ],
/** 0x34 **/[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
/** 0x35 **/[ arm.CMP, arm.CMP, arm.CMP, arm.CMP, arm.CMP, arm.CMP, arm.CMP, arm.CMP, arm.CMP, arm.CMP, arm.CMP, arm.CMP, arm.CMP, arm.CMP, arm.CMP, arm.CMP],
/** 0x36 **/[arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR,arm.MSR],
/** 0x37 **/[ arm.CMN, arm.CMN, arm.CMN, arm.CMN, arm.CMN, arm.CMN, arm.CMN, arm.CMN, arm.CMN, arm.CMN, arm.CMN, arm.CMN, arm.CMN, arm.CMN, arm.CMN, arm.CMN],
/** 0x38 **/[ arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR],
/** 0x39 **/[ arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR, arm.ORR],
/** 0x3a **/[ arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV],
/** 0x3b **/[ arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV, arm.MOV],
/** 0x3c **/[ arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC],
/** 0x3d **/[ arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC, arm.BIC],
/** 0x3e **/[ arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN],
/** 0x3f **/[ arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN, arm.MVN],
/** 0x40 **/[ arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR],
/** 0x41 **/[ arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR],
/** 0x42 **/[ arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT],
/** 0x43 **/[ arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT],
/** 0x44 **/[ arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB],
/** 0x45 **/[ arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB],
/** 0x46 **/[ arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT],
/** 0x47 **/[ arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT],
/** 0x48 **/[ arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR],
/** 0x49 **/[ arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR],
/** 0x4a **/[ arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT, arm.STRT],
/** 0x4b **/[ arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT, arm.LDRT],
/** 0x4c **/[ arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB],
/** 0x4d **/[ arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB],
/** 0x4e **/[ arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT, arm.STRBT],
/** 0x4f **/[ arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT, arm.LDRBT],
/** 0x50 **/[ arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR],
/** 0x51 **/[ arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR],
/** 0x52 **/[ arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR],
/** 0x53 **/[ arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR],
/** 0x54 **/[ arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB],
/** 0x55 **/[ arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB],
/** 0x56 **/[ arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB],
/** 0x57 **/[ arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB],
/** 0x58 **/[ arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR],
/** 0x59 **/[ arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR],
/** 0x5a **/[ arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR, arm.STR],
/** 0x5b **/[ arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR, arm.LDR],
/** 0x5c **/[ arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB],
/** 0x5d **/[ arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB],
/** 0x5e **/[ arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB, arm.STRB],
/** 0x5f **/[ arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB, arm.LDRB],
/** 0x60 **/[ arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null],
/** 0x61 **/[ arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null],
/** 0x62 **/[ arm.STRT,null, arm.STRT,null, arm.STRT,null, arm.STRT,null, arm.STRT,null, arm.STRT,null, arm.STRT,null, arm.STRT,null],
/** 0x63 **/[ arm.LDRT,null, arm.LDRT,null, arm.LDRT,null, arm.LDRT,null, arm.LDRT,null, arm.LDRT,null, arm.LDRT,null, arm.LDRT,null],
/** 0x64 **/[ arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null],
/** 0x65 **/[ arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null],
/** 0x66 **/[ arm.STRBT,null, arm.STRBT,null, arm.STRBT,null, arm.STRBT,null, arm.STRBT,null, arm.STRBT,null, arm.STRBT,null, arm.STRBT,null],
/** 0x67 **/[ arm.LDRBT,null, arm.LDRBT,null, arm.LDRBT,null, arm.LDRBT,null, arm.LDRBT,null, arm.LDRBT,null, arm.LDRBT,null, arm.LDRBT,null],
/** 0x68 **/[ arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null],
/** 0x69 **/[ arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null],
/** 0x6a **/[ arm.STRT,null, arm.STRT,null, arm.STRT,null, arm.STRT,null, arm.STRT,null, arm.STRT,null, arm.STRT,null, arm.STRT,null],
/** 0x6b **/[ arm.LDRT,null, arm.LDRT,null, arm.LDRT,null, arm.LDRT,null, arm.LDRT,null, arm.LDRT,null, arm.LDRT,null, arm.LDRT,null],
/** 0x6c **/[ arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null],
/** 0x6d **/[ arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null],
/** 0x6e **/[ arm.STRBT,null, arm.STRBT,null, arm.STRBT,null, arm.STRBT,null, arm.STRBT,null, arm.STRBT,null, arm.STRBT,null, arm.STRBT,null],
/** 0x6f **/[ arm.LDRBT,null, arm.LDRBT,null, arm.LDRBT,null, arm.LDRBT,null, arm.LDRBT,null, arm.LDRBT,null, arm.LDRBT,null, arm.LDRBT,null],
/** 0x70 **/[ arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null],
/** 0x71 **/[ arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null],
/** 0x72 **/[ arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null],
/** 0x73 **/[ arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null],
/** 0x74 **/[ arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null],
/** 0x75 **/[ arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null],
/** 0x76 **/[ arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null],
/** 0x77 **/[ arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null],
/** 0x78 **/[ arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null],
/** 0x79 **/[ arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null],
/** 0x7a **/[ arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null, arm.STR,null],
/** 0x7b **/[ arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null, arm.LDR,null],
/** 0x7c **/[ arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null],
/** 0x7d **/[ arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null],
/** 0x7e **/[ arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null, arm.STRB,null],
/** 0x7f **/[ arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null, arm.LDRB,null],
/** 0x80 **/[ arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2],
/** 0x81 **/[ arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM],
/** 0x82 **/[ arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2],
/** 0x83 **/[ arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM],
/** 0x84 **/[ arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM],
/** 0x85 **/[ arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2],
/** 0x86 **/[ arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM],
/** 0x87 **/[ arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2],
/** 0x88 **/[ arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2],
/** 0x89 **/[ arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM],
/** 0x8a **/[ arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2],
/** 0x8b **/[ arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM],
/** 0x8c **/[ arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM],
/** 0x8d **/[ arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2],
/** 0x8e **/[ arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM],
/** 0x8f **/[ arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2],
/** 0x90 **/[ arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2],
/** 0x91 **/[ arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM],
/** 0x92 **/[ arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2],
/** 0x93 **/[ arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM],
/** 0x94 **/[ arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM],
/** 0x95 **/[ arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2],
/** 0x96 **/[ arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM],
/** 0x97 **/[ arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2],
/** 0x98 **/[ arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2],
/** 0x99 **/[ arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM],
/** 0x9a **/[ arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2, arm.STM2],
/** 0x9b **/[ arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM, arm.LDM],
/** 0x9c **/[ arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM],
/** 0x9d **/[ arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2],
/** 0x9e **/[ arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM, arm.STM],
/** 0x9f **/[ arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2, arm.LDM2],
/** 0xa0 **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xa1 **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xa2 **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xa3 **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xa4 **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xa5 **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xa6 **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xa7 **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xa8 **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xa9 **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xaa **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xab **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xac **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xad **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xae **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xaf **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xb0 **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xb1 **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xb2 **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xb3 **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xb4 **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xb5 **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xb6 **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xb7 **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xb8 **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xb9 **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xba **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xbb **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xbc **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xbd **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xbe **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xbf **/[arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL,arm.BBL],
/** 0xc0 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xc1 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xc2 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xc3 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xc4 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xc5 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xc6 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xc7 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xc8 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xc9 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xca **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xcb **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xcc **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xcd **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xce **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xcf **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xd0 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xd1 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xd2 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xd3 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xd4 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xd5 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xd6 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xd7 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xd8 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xd9 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xda **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xdb **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xdc **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xdd **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xde **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xdf **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xe0 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xe1 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xe2 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xe3 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xe4 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xe5 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xe6 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xe7 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xe8 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xe9 **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xea **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xeb **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xec **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xed **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xee **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xef **/[ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
/** 0xf0 **/[arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI],
/** 0xf1 **/[arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI],
/** 0xf2 **/[arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI],
/** 0xf3 **/[arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI],
/** 0xf4 **/[arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI],
/** 0xf5 **/[arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI],
/** 0xf6 **/[arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI],
/** 0xf7 **/[arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI],
/** 0xf8 **/[arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI],
/** 0xf9 **/[arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI],
/** 0xfa **/[arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI],
/** 0xfb **/[arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI],
/** 0xfc **/[arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI],
/** 0xfd **/[arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI],
/** 0xfe **/[arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI],
/** 0xff **/[arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI,arm.SWI]
]